server:
  port: 8090  #服务端口号
spring:
  #进行热部署需要的配置
  devtools: 
    restart: 
      enabled: true
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/violet
    username: root
    password: 253613
  #jpa需要的配置
  jpa:
    hibernate:
      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
    show-sql: true
